/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.Icones;

import Dao.CartuchoDao;
import Dao.ConexaoJdbc;
import Dao.UsuarioDao;
import controller.Cartucho;
import controller.Usuario;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author israe
 */
public class TelaCartucho extends javax.swing.JDialog {

    /**
     * Creates new form TelaCartucho
     */
    public TelaCartucho(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarComboBoxImpressora();
        //listarCartuchos();
        desabilitarCampos();
        desabilitarBotoes();
        receberUsuarioLogado();
        btnBuscar.requestFocus(true);
        this.tabelaAlterarCartuchoTeste = new TelaTableAlterarCartucho(parent, rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCartuchos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnImprimirRelatorio = new javax.swing.JButton();
        btnEstoqueCartucho = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtModelo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JComboBox<>();
        comboBoxImpressora = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboBoxSetor = new javax.swing.JComboBox<>();
        btnInserirImpressora = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        giroQuantidade = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        labelVoltar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        radioBuscarTodos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Cartuchos");

        tabelaCartuchos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tabelaCartuchos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "MODELO", "TIPO", "IMPRESSORA", "SETOR IMPRESSORA", "COR", "QUANTIDADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCartuchos.setToolTipText("Estoque atual de Cartuchos");
        tabelaCartuchos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCartuchosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCartuchos);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botões", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        btnImprimirRelatorio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnImprimirRelatorio.setText("Relatório");
        btnImprimirRelatorio.setToolTipText("Clique aqui para imprimir um relatório sobre cartuchos");
        btnImprimirRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimirRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirRelatorioActionPerformed(evt);
            }
        });

        btnEstoqueCartucho.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnEstoqueCartucho.setText("Estoque");
        btnEstoqueCartucho.setToolTipText("Clique aqui para movimentar o estoque de cartuchos");
        btnEstoqueCartucho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstoqueCartucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueCartuchoActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Clique aqui para cadastrar um novo cartucho");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Clique aqui para sallvar operações iniciadas");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("Clique aqui para alterar um item.");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Clique aqui para cancelar a operação iniciada");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Clique aqui para excluir um item.");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstoqueCartucho, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimirRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimirRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstoqueCartucho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Campos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        txtModelo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtModelo.setToolTipText("Digite o modelo do cartucho");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Modelo");

        txtTipo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TONER", "TINTA", "CARTUCHO" }));

        comboBoxImpressora.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        comboBoxImpressora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Impressora" }));
        comboBoxImpressora.setToolTipText("Selecione a impressora");
        comboBoxImpressora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxImpressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxImpressoraActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Impressora");

        comboBoxSetor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        comboBoxSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Setor" }));
        comboBoxSetor.setToolTipText("Selecione o setor");
        comboBoxSetor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnInserirImpressora.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnInserirImpressora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/add_1.png"))); // NOI18N
        btnInserirImpressora.setToolTipText("Clique aqui para inserir uma nova impressora");
        btnInserirImpressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirImpressoraActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Setor Impressora");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Adc. Impr.");

        giroQuantidade.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        giroQuantidade.setToolTipText("Para alterar a quantidade em estoque, use o módulo de Gerenciamento de Estoque de Cartuchos");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Quantidade");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Cor");

        txtCor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRETO", "AMARELO", "AZUL", "VERMELHO" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Tipo");

        labelVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/Logout_37127.png"))); // NOI18N
        labelVoltar.setToolTipText("Voltar");
        labelVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelVoltar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                labelVoltarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        labelVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtCor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(comboBoxImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnInserirImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(giroQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(labelVoltar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnInserirImpressora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(giroQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/magnifier.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarKeyPressed(evt);
            }
        });

        radioBuscarTodos.setSelected(true);
        radioBuscarTodos.setText("Buscar Todos");
        radioBuscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBuscarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioBuscarTodos)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(radioBuscarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private TelaTableAlterarCartucho tabelaAlterarCartuchoTeste;
    private Integer idCartucho;
    
        public void receberUsuarioLogado(){
        UsuarioDao ud = new UsuarioDao();
        String usuario = ud.getUsuarioLogado();
        int idUsuarioLogado = ud.getIdUsuarioLogado(usuario);
        String adm = ud.verSeUsuarioEadm(idUsuarioLogado);
        
        if(adm.equals("nao")){
            btnEstoqueCartucho.setEnabled(false);   
            btnSalvar.setEnabled(false);   
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnNovo.setEnabled(false);
        } 
    }
    
    private void comboBoxImpressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxImpressoraActionPerformed
        if(!comboBoxImpressora.getSelectedItem().equals("Impressora")){
            comboBoxSetor.removeAllItems();
            CartuchoDao cd = new CartuchoDao();
            String impressora = (String) comboBoxImpressora.getSelectedItem();
            int idImpressora = cd.getIdJcomboBoxImpressora(impressora);
            int idSetor = cd.getIdSetorImpressora(idImpressora);
            String setor = cd.getSetorCartucho(idSetor);
            comboBoxSetor.addItem(setor);
            comboBoxSetor.setSelectedItem(setor);
        }else{
            comboBoxSetor.removeAllItems();
            comboBoxSetor.addItem("Setor");
            comboBoxSetor.setSelectedItem("Setor");
        }

    }//GEN-LAST:event_comboBoxImpressoraActionPerformed

    private void labelVoltarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_labelVoltarAncestorAdded
        //
    }//GEN-LAST:event_labelVoltarAncestorAdded

    private void labelVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVoltarMouseClicked
       dispose();
    }//GEN-LAST:event_labelVoltarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        desabilitarBotoes();
        desabilitarCampos();
        limparCampos();
        btnNovo.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limparCampos();
        habilitarCampos();
        btnNovo.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
    }//GEN-LAST:event_btnNovoActionPerformed
       
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //Verificando se o botão alterar está desabilitado.
        //Salvando um novo Cartucho.
        if(!btnAlterar.isEnabled() && !btnExcluir.isEnabled()){
            if(txtModelo.getText().equals("") || txtTipo.getSelectedItem().equals("") || txtCor.getSelectedItem().equals("") ||
               comboBoxImpressora.getSelectedItem().equals("Impressora") || comboBoxSetor.getSelectedItem().equals("Setor")){
                JOptionPane.showMessageDialog(null, "Preecha todos os campos.".toUpperCase());            
            }
            else
            {
                String modelo = txtModelo.getText().toUpperCase();
                CartuchoDao cd = new CartuchoDao();
                if(cd.verSeCartuchoEstaCadastrado(modelo) == true){
                    String tipo = txtTipo.getSelectedItem().toString();
                    int quantidade = (int) giroQuantidade.getValue();
                    String cor = txtCor.getSelectedItem().toString();
                    String impressora = comboBoxImpressora.getSelectedItem().toString();

                    int idImpressora = cd.getIdJcomboBoxImpressora(impressora);

                    Cartucho cartucho = new Cartucho();
                    cartucho.setCor(cor);
                    cartucho.setImpressora(idImpressora);
                    cartucho.setModelo(modelo);
                    cartucho.setQuantidade(quantidade);
                    cartucho.setTipo(tipo);

                    if(cd.salvar(cartucho)){
                        JOptionPane.showMessageDialog(null, "Cartucho incluído com sucesso.".toUpperCase());
                        listarCartuchos();
                        limparCampos();
                        desabilitarCampos();
                        desabilitarBotoes();
                        btnNovo.setEnabled(true);
                        btnAlterar.setEnabled(true);
                        btnExcluir.setEnabled(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "Erro ao inserir cartucho.".toUpperCase());
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Esse cartucho já está cadastrado.".toUpperCase());
                    txtModelo.requestFocus(true);
                }
            }
        }//Verificando se o botão alterar está habilitado e o botão excluir desabilitado.
        //Alterando um cartucho.
        else if(btnAlterar.isEnabled()==true && btnExcluir.isEnabled()==false){
            if(txtModelo.getText().equals("") || txtTipo.getSelectedItem().equals("") || txtCor.getSelectedItem().equals("") ||
               comboBoxImpressora.getSelectedItem().equals("Impressora") || comboBoxSetor.getSelectedItem().equals("Setor")){
               JOptionPane.showMessageDialog(null, "Preecha todos os campos.".toUpperCase());            
            }
            else
            {
                String modelo = txtModelo.getText().toUpperCase();
                String tipo = txtTipo.getSelectedItem().toString();
                String cor = txtCor.getSelectedItem().toString();
                String impressora = comboBoxImpressora.getSelectedItem().toString();
                
                CartuchoDao cd = new CartuchoDao();
                
                int idImpressora = cd.getIdJcomboBoxImpressora(impressora);
                
                Cartucho cartucho = new Cartucho();
                cartucho.setCor(cor);
                cartucho.setImpressora(idImpressora);
                cartucho.setModelo(modelo);
                cartucho.setTipo(tipo);
                
                if(cd.editar(cartucho,idCartucho)){
                    JOptionPane.showMessageDialog(null, "Cartucho alterado com sucesso.".toUpperCase());
                    listarCartuchos();
                    limparCampos();
                    desabilitarCampos();
                    desabilitarBotoes();
                    btnNovo.setEnabled(true);
                    btnExcluir.setEnabled(true);
                    clearItensTableAlterarCartucho();
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao alterar cartucho.".toUpperCase());
                }
            }
        }//Verificando se o botão excluir está habilitado e o botão alterar desabilitado.
        //Excluindo um cartucho.
        /*else if(btnExcluir.isEnabled()==true && btnAlterar.isEnabled()==false){
                      
            CartuchoDao cd = new CartuchoDao();
                        
            Cartucho cartucho = new Cartucho();
            
            int teste = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o item selecionado?", "Confirmar exclusão", JOptionPane.YES_NO_OPTION);

            if(teste == JOptionPane.YES_OPTION){
                if(cd.excluir(cartucho, idCartucho)){
                JOptionPane.showMessageDialog(null, "Cartucho excluído com sucesso.".toUpperCase());
                cd.cleanAutoIncrementTableCartucho();
                listarCartuchos();
                limparCampos();
                desabilitarCampos();
                desabilitarBotoes();
                btnNovo.setEnabled(true);
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
                clearItensTableAlterarCartucho();
                }
            }
            else if (teste == JOptionPane.NO_OPTION)
            {
                JOptionPane.showMessageDialog(null, "Operação não realizada.", "Exclusão cancelada", JOptionPane.INFORMATION_MESSAGE);
            }
        }*/else{
            JOptionPane.showMessageDialog(null, "Feche esta janela e tente realizar a operação mais uma vez.".toUpperCase());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed
    //Passando dados da tabela da TelaTableAlterarCartucho para a tela Cartucho.
    public void getItensTableAlterarCartucho(){
        this.tabelaAlterarCartuchoTeste.setVisible(true);
        this.tabelaAlterarCartuchoTeste.listarCartuchos();
        
        this.idCartucho = Integer.parseInt(tabelaAlterarCartuchoTeste.getIdCartucho());
        this.txtTipo.setSelectedItem(String.valueOf(tabelaAlterarCartuchoTeste.getTipo()));
        this.txtModelo.setText(String.valueOf(tabelaAlterarCartuchoTeste.getModelo()));
        this.comboBoxImpressora.setSelectedItem(String.valueOf(tabelaAlterarCartuchoTeste.getImpressora()));
        this.txtCor.setSelectedItem(String.valueOf(tabelaAlterarCartuchoTeste.getCor()));
        this.giroQuantidade.setValue(Integer.valueOf(tabelaAlterarCartuchoTeste.getQuantidade()));
    }
    
        public void clearItensTableAlterarCartucho(){
        tabelaAlterarCartuchoTeste.setModelo("");
        tabelaAlterarCartuchoTeste.setTipo("");
        tabelaAlterarCartuchoTeste.setImpressora("Impressora");
        tabelaAlterarCartuchoTeste.setCor("");
        tabelaAlterarCartuchoTeste.setQuantidade(0);
    }
    
    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        //método para chamar a tela TableAlterarCartucho.
        //teste para atualizar tabela TableAlterar Cartucho.
        //this.tabelaAlterarCartuchoTeste.listarCartuchos();
        //getItensTableAlterarCartucho();
        
        int linha = tabelaCartuchos.getSelectedRow();
        
        if(linha > -1 && this.coletaDadosTabela == true){
            btnNovo.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnInserirImpressora.setEnabled(false);
            btnSalvar.setEnabled(true);
            this.idCartucho = (Integer) tabelaCartuchos.getModel().getValueAt(linha, 0); 
            habilitarCampos();
        }
        else{
            JOptionPane.showMessageDialog(null, "Escolha um item da lista para alterá-lo.".toUpperCase());
            btnCancelar.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnNovo.setEnabled(true);
            btnExcluir.setEnabled(true);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        btnNovo.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnInserirImpressora.setEnabled(false);
        //método para chamar a tela TableAlterarCartucho.
        //teste para atualizar tabela TableAlterar Cartucho.
        //this.tabelaAlterarCartuchoTeste.listarCartuchos();
        //getItensTableAlterarCartucho();
        
        int linha = tabelaCartuchos.getSelectedRow();
        
        if(linha > -1 && coletaDadosTabela == true){
            this.idCartucho = (Integer) tabelaCartuchos.getModel().getValueAt(linha, 0); 
                if(btnExcluir.isEnabled()==true && btnAlterar.isEnabled()==false){
                      
                CartuchoDao cd = new CartuchoDao();

                Cartucho cartucho = new Cartucho();

                int teste = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o item selecionado?", "Confirmar exclusão", JOptionPane.YES_NO_OPTION);

                    if(teste == JOptionPane.YES_OPTION){
                        if(cd.excluir(cartucho, idCartucho)){
                        JOptionPane.showMessageDialog(null, "Cartucho excluído com sucesso.".toUpperCase());
                        cd.cleanAutoIncrementTableCartucho();
                        listarCartuchos();
                        limparCampos();
                        desabilitarCampos();
                        desabilitarBotoes();
                        btnNovo.setEnabled(true);
                        btnAlterar.setEnabled(true);
                        btnExcluir.setEnabled(true);
                        clearItensTableAlterarCartucho();
                        coletaDadosTabela = false;
                        }
                    }
                    else if (teste == JOptionPane.NO_OPTION)
                    {
                        JOptionPane.showMessageDialog(null, "Operação não realizada.", "Exclusão cancelada", JOptionPane.INFORMATION_MESSAGE);
                        btnCancelar.setEnabled(true);
                        btnSalvar.setEnabled(false);
                        btnNovo.setEnabled(true);
                        coletaDadosTabela = false;
                        limparCampos();
                    }
                    }else{
                        JOptionPane.showMessageDialog(null, "Feche esta janela e tente realizar a operação mais uma vez.".toUpperCase());
                    }
                }
                else
                {
                JOptionPane.showMessageDialog(null, "Escolha um item da lista para excluí-lo.".toUpperCase());
                btnCancelar.setEnabled(false);
                btnSalvar.setEnabled(false);
                btnNovo.setEnabled(true);
                btnAlterar.setEnabled(true);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private Toolkit tk = Toolkit.getDefaultToolkit();
    private Dimension d = tk.getScreenSize();
    
    private void btnImprimirRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirRelatorioActionPerformed
        String src = "C:\\Tontech\\relatorios\\selectCartuchos.jasper";
            Connection con = ConexaoJdbc.getConnection();
            JDialog viewer = new JDialog(new javax.swing.JFrame(), "Relatório", true);  
            //Pega a Resolução do Video  
            viewer.setSize(d.width, d.height-25);  
            viewer.setLocationRelativeTo(null);  
            //Deixar true pois da problema no relatorio caso deixado false  
            viewer.setResizable(true);  
            JasperPrint jasperPrint;  
            try {
                //Instanciando o JasperFillManager.fillReport no caminho src, sem parametros (null) e a conexão con para o select do banco.
                jasperPrint = JasperFillManager.fillReport(src, null, con);
                
                JasperViewer jrViewer = new JasperViewer(jasperPrint, true);  
                
                //Adicionando o relatorio no Jdialog  
                viewer.getContentPane().add(jrViewer.getContentPane());
                
                //Deixar True para exibir a tela no sistema  
                viewer.setVisible(true);  
                
            } catch (JRException ex) {
                Logger.getLogger(TelaEstoque.class.getName()).log(Level.SEVERE, null, ex);
            }    
    }//GEN-LAST:event_btnImprimirRelatorioActionPerformed

    private void btnEstoqueCartuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueCartuchoActionPerformed
        TelaMovimentarEstoque tela = new TelaMovimentarEstoque(null, rootPaneCheckingEnabled);
        tela.setVisible(true);
    }//GEN-LAST:event_btnEstoqueCartuchoActionPerformed

    private void btnInserirImpressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirImpressoraActionPerformed
        TelaImpressora2 tela = new TelaImpressora2(null, rootPaneCheckingEnabled);
        tela.setVisible(true);
    }//GEN-LAST:event_btnInserirImpressoraActionPerformed
    
    boolean coletaDadosTabela = false;
    private void tabelaCartuchosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCartuchosMouseClicked
        if(evt.getClickCount() == 2){
            int linha = tabelaCartuchos.getSelectedRow();
        
            if(linha > -1){
                int idCartucho = (int) tabelaCartuchos.getModel().getValueAt(linha, 0);
                String tipo = tabelaCartuchos.getModel().getValueAt(linha, 2).toString();
                String modelo = tabelaCartuchos.getModel().getValueAt(linha, 1).toString();
                String impressora = tabelaCartuchos.getModel().getValueAt(linha, 3).toString();
                String cor = tabelaCartuchos.getModel().getValueAt(linha, 5).toString();
                
                CartuchoDao cd = new CartuchoDao();
                int quantidade = cd.getEstoque(idCartucho);
                
                //passando dados da tabela para os campos.
                txtModelo.setText(modelo);
                txtTipo.setSelectedItem(tipo);
                comboBoxImpressora.setSelectedItem(impressora);
                txtCor.setSelectedItem(cor);
                this.coletaDadosTabela = true;
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Selecione um cartucho para prosseguir!".toUpperCase());
                this.coletaDadosTabela = false;
            }
        }
        else if(evt.getButton() == 3){
            tabelaCartuchos.getSelectionModel().clearSelection();
            this.coletaDadosTabela = false;
        }
    }//GEN-LAST:event_tabelaCartuchosMouseClicked

    public void listarCartuchosComLike(String buscar){
        
        CartuchoDao cd = new CartuchoDao();
            
        List<Cartucho> listaCartucho = cd.listaCartuchoTelaTableComLike(buscar);

        DefaultTableModel modelo = (DefaultTableModel) tabelaCartuchos.getModel();

        modelo.setNumRows(0);

        for (Cartucho c : cd.listaCartuchoTelaTableComLike(buscar)) {

            modelo.addRow(new Object[]{
                c.getIdCartucho(),
                c.getModelo(),
                c.getTipo(),
                c.getModeloImpressora(),
                c.getSetor(),
                c.getCor(),
                c.getQuantidade()
            });

        }

        tabelaCartuchos.setModel(modelo);

        tabelaCartuchos.getColumnModel().getColumn(0).setPreferredWidth(70);
        tabelaCartuchos.getColumnModel().getColumn(1).setPreferredWidth(160);
        tabelaCartuchos.getColumnModel().getColumn(2).setPreferredWidth(110);
        tabelaCartuchos.getColumnModel().getColumn(3).setPreferredWidth(190);
        tabelaCartuchos.getColumnModel().getColumn(4).setPreferredWidth(175);
        tabelaCartuchos.getColumnModel().getColumn(5).setPreferredWidth(120);
        tabelaCartuchos.getColumnModel().getColumn(6).setPreferredWidth(102);
    }
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if(radioBuscarTodos.isSelected()==true){
            listarCartuchos();
            txtBuscar.requestFocus(true);
        }
        else{
            String buscar = txtBuscar.getText().toUpperCase();
        
            if(!buscar.equals("")){
                listarCartuchosComLike(buscar);
                txtBuscar.setText("");
                txtBuscar.requestFocus(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Digite um termo para pesquisa.".toUpperCase());
                txtBuscar.requestFocus(true);
            }
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        if(!txtBuscar.getText().equals("") && radioBuscarTodos.isSelected()==false){
            btnBuscar.requestFocus(true);
        }
        else if(txtBuscar.getText().equals("") && radioBuscarTodos.isSelected()==true){
            btnBuscar.requestFocus(true);
        }else{
            JOptionPane.showMessageDialog(null, "Digite um termo para pesquisa.".toUpperCase());
        }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void radioBuscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBuscarTodosActionPerformed
        if(radioBuscarTodos.isSelected()== true){
            btnBuscar.requestFocus(true);
        }else if(radioBuscarTodos.isSelected()== false){
            txtBuscar.requestFocus(true);
        }
    }//GEN-LAST:event_radioBuscarTodosActionPerformed

    private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(radioBuscarTodos.isSelected()==true){
            listarCartuchos();
            txtBuscar.requestFocus(true);
            }
            else
            {
            String buscar = txtBuscar.getText().toUpperCase();
        
            if(!buscar.equals("")){
                listarCartuchosComLike(buscar);
                txtBuscar.setText("");
                txtBuscar.requestFocus(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Digite um termo para pesquisa.".toUpperCase());
                txtBuscar.requestFocus(true);
            }
            }
        }
        
    }//GEN-LAST:event_btnBuscarKeyPressed

    public void carregarComboBoxImpressora(){
        CartuchoDao cd = new CartuchoDao();
        cd.carregarJcomboBox(comboBoxImpressora);
    }
    
    public void desabilitarCampos(){
        txtModelo.setEnabled(false);
        giroQuantidade.setEnabled(false);
        txtTipo.setEnabled(false);
        txtCor.setEnabled(false);
        comboBoxImpressora.setEnabled(false);
        comboBoxSetor.setEnabled(false);
    }
    
    public void desabilitarBotoes(){
        btnSalvar.setEnabled(false);
        /*btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);*/
        btnCancelar.setEnabled(false);
        btnInserirImpressora.setEnabled(false);
    }
    
    public void habilitarCampos(){
        txtModelo.setEnabled(true);
        //giroQuantidade.setEnabled(true);
        txtTipo.setEnabled(true);
        txtCor.setEnabled(true);
        comboBoxImpressora.setEnabled(true);
        comboBoxSetor.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnInserirImpressora.setEnabled(true);
    }
    
    public void limparCampos(){
        txtModelo.setText("");
        giroQuantidade.setValue(0);
        txtTipo.setSelectedItem("TONER");
        txtCor.setSelectedItem("PRETO");
        comboBoxImpressora.setSelectedItem("Impressora");
        comboBoxSetor.removeAllItems();
        comboBoxSetor.addItem("Setor");
        comboBoxSetor.setSelectedItem("Setor");
    }
    
    public void listarCartuchos (){
        
        CartuchoDao cd = new CartuchoDao();
        
        List<Cartucho> listarCartucho = cd.selectCartucho();
           
        DefaultTableModel modelo = (DefaultTableModel) tabelaCartuchos.getModel();
        
        //Para a tabela não definir a largura das colunas de forma automática.
        //tabelaCartuchos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        modelo.setNumRows(0);
        
        for (Cartucho c : cd.selectCartucho()) {

            modelo.addRow(new Object[]{
                c.getIdCartucho(),
                c.getModelo(),
                c.getTipo(),
                c.getModeloImpressora(),
                c.getSetor(),
                c.getCor(),
                c.getQuantidade()
            });

        }
        
        //Definindo a largura das colunas da tabela tabelaCartuchos.
        tabelaCartuchos.getColumnModel().getColumn(0).setPreferredWidth(70);
        tabelaCartuchos.getColumnModel().getColumn(1).setPreferredWidth(160);
        tabelaCartuchos.getColumnModel().getColumn(2).setPreferredWidth(110);
        tabelaCartuchos.getColumnModel().getColumn(3).setPreferredWidth(190);
        tabelaCartuchos.getColumnModel().getColumn(4).setPreferredWidth(175);
        tabelaCartuchos.getColumnModel().getColumn(5).setPreferredWidth(120);
        tabelaCartuchos.getColumnModel().getColumn(6).setPreferredWidth(102);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCartucho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCartucho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCartucho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCartucho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCartucho dialog = new TelaCartucho(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEstoqueCartucho;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnImprimirRelatorio;
    private javax.swing.JButton btnInserirImpressora;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comboBoxImpressora;
    private javax.swing.JComboBox<String> comboBoxSetor;
    private javax.swing.JSpinner giroQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelVoltar;
    private javax.swing.JRadioButton radioBuscarTodos;
    private javax.swing.JTable tabelaCartuchos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JComboBox<String> txtCor;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JComboBox<String> txtTipo;
    // End of variables declaration//GEN-END:variables
}
