/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.Icones;

import Dao.NotificacaoDao;
import Dao.UsuarioDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Israel
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        //receberUsuarioLogado();
        countNotificacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iconEstoque = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IconSair = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelImpressoraPrincipal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnNotificacao = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNotificacao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuCartucho = new javax.swing.JMenuItem();
        MenuImpressora = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de Impressoras e cartuchos");
        setPreferredSize(new java.awt.Dimension(1150, 800));
        setSize(new java.awt.Dimension(1150, 800));

        jPanel1.setPreferredSize(new java.awt.Dimension(1140, 163));

        jLabel1.setText("Cartuchos");

        iconEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/estoque.png"))); // NOI18N
        iconEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconEstoqueMouseClicked(evt);
            }
        });

        jLabel2.setText("Sair");

        IconSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/sair.png"))); // NOI18N
        IconSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IconSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconSairMouseClicked(evt);
            }
        });

        jLabel3.setText("Impressoras");

        jLabelImpressoraPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/impressoraPrincipal.png"))); // NOI18N
        jLabelImpressoraPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelImpressoraPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelImpressoraPrincipalMouseClicked(evt);
            }
        });

        jLabel5.setText("Controle de usuarios");

        jLabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/user_customer_person_13976.png"))); // NOI18N
        jLabelUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUsuarioMouseClicked(evt);
            }
        });

        jLabel7.setText("Notificações");

        btnNotificacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/notificacao.png"))); // NOI18N
        btnNotificacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNotificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacaoActionPerformed(evt);
            }
        });

        jLabel8.setText("(");

        jLabel9.setText(")");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconEstoque)
                    .addComponent(jLabel1))
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelImpressoraPrincipal)
                        .addGap(114, 114, 114)
                        .addComponent(jLabelUsuario)))
                .addGap(142, 142, 142)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNotificacao)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)
                        .addComponent(txtNotificacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(IconSair)
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtNotificacao))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(iconEstoque)
                            .addComponent(IconSair)
                            .addComponent(jLabelImpressoraPrincipal))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNotificacao)
                        .addContainerGap(36, Short.MAX_VALUE))))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(1150, 36));

        labelUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Usuário:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        jMenu1.setText("Arquivos");

        MenuCartucho.setText("Cartuchos");
        MenuCartucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCartuchoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCartucho);

        MenuImpressora.setText("Impressoras");
        MenuImpressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuImpressoraActionPerformed(evt);
            }
        });
        jMenu1.add(MenuImpressora);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1150, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 646, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /*public void receberUsuarioLogado(){
        UsuarioDao ud = new UsuarioDao();
        String usuario;
        usuario = ud.getUsuarioLogado();
        //txtUsuario.setText(usuario);
        int idUsuarioLogado = ud.getIdUsuarioLogado(usuario);
        String adm = ud.verSeUsuarioEadm(idUsuarioLogado);
    }*/
    
    public String usuarioAdmOuNao(){
        UsuarioDao ud = new UsuarioDao();
        String usuario = ud.getUsuarioLogado();
        int idUsuario = ud.getIdUsuarioLogado(usuario);
        String adm = ud.verSeUsuarioEadm(idUsuario);
        return adm;
    }
    
    public void countNotificacao(){
        NotificacaoDao ntfd = new NotificacaoDao();
        String count = ntfd.countNotificacao();
        txtNotificacao.setText(count);
    }
    
    private void iconEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconEstoqueMouseClicked
    TelaEstoque telaEstoque = new TelaEstoque(this, rootPaneCheckingEnabled);
    telaEstoque.setVisible(true);      
    }//GEN-LAST:event_iconEstoqueMouseClicked

    private void IconSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_IconSairMouseClicked

    private void MenuCartuchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCartuchoActionPerformed
        TelaEstoque telaEstoque = new TelaEstoque(this, rootPaneCheckingEnabled);
        telaEstoque.setVisible(true);
    }//GEN-LAST:event_MenuCartuchoActionPerformed

    private void jLabelImpressoraPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelImpressoraPrincipalMouseClicked
        if(jLabelImpressoraPrincipal.isEnabled()){
            TelaImpressora2 telaImpressora = new TelaImpressora2(this, rootPaneCheckingEnabled);
            telaImpressora.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Você não tem permissão de administrador.");
        }
       
    }//GEN-LAST:event_jLabelImpressoraPrincipalMouseClicked

    private void MenuImpressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuImpressoraActionPerformed
        TelaImpressora2 telaImpressora = new TelaImpressora2(this, rootPaneCheckingEnabled);
        telaImpressora.setVisible(true);
    }//GEN-LAST:event_MenuImpressoraActionPerformed

    private void jLabelUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUsuarioMouseClicked
        String usuarioAdm = usuarioAdmOuNao();
        
        if(usuarioAdm.equals("sim")){
            TelaControleUsuario telaUsuario = new TelaControleUsuario(this, rootPaneCheckingEnabled);
            telaUsuario.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Você não tem permissão de administrador.");
        }
        
    }//GEN-LAST:event_jLabelUsuarioMouseClicked

    private void btnNotificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacaoActionPerformed
        String usuarioAdm = usuarioAdmOuNao();
        
        if(usuarioAdm.equals("sim")){
            TelaVerNotificacao verNotificacao = new TelaVerNotificacao(this, rootPaneCheckingEnabled);
            verNotificacao.setVisible(true);
        }
        else{
            TelaInserirNotificacao inserirNotificacao = new TelaInserirNotificacao(this, rootPaneCheckingEnabled);
            inserirNotificacao.setVisible(true);
        }
        
    }//GEN-LAST:event_btnNotificacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconSair;
    private javax.swing.JMenuItem MenuCartucho;
    private javax.swing.JMenuItem MenuImpressora;
    private javax.swing.JButton btnNotificacao;
    private javax.swing.JLabel iconEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImpressoraPrincipal;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel txtNotificacao;
    // End of variables declaration//GEN-END:variables
}
