/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.Icones;

import Dao.FabricanteDao;
import controller.Fabricante;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author israe
 */
public class TelaFabricante extends javax.swing.JDialog {

    /**
     * Creates new form TelaFabricante
     */
    public TelaFabricante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listarFabricante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtFabricante = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fabricantes");
        setPreferredSize(new java.awt.Dimension(958, 745));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "FABRICANTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
        }

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalvar.setText("Cadastrar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Fabricante:");

        txtFabricante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 468, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
    if(evt.getClickCount() == 2){
        int linha = getLinhaTable();
        if(linha > -1){
            btnSalvar.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            String fabricante = getValorLinhaTable(linha, 1);
            txtFabricante.setText(fabricante);
            txtFabricante.requestFocus();
        }
    }
    else if(evt.getButton() == 3){
        tabela.getSelectionModel().clearSelection();
        btnSalvar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        limparCampos();
    }
    }//GEN-LAST:event_tabelaMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Fabricante fabricante = new Fabricante();
        FabricanteDao fd = new FabricanteDao();
        String nomeFabricante = txtFabricante.getText().toUpperCase();
        boolean fabricanteNaoCadastrado = fd.verSeFabricanteCadastrado(nomeFabricante);
        if(!nomeFabricante.equals("")){
            if(fabricanteNaoCadastrado == true){
                fabricante.setNome(nomeFabricante);
                if(fd.salvar(fabricante) == true){
                    JOptionPane.showMessageDialog(null, "Fabricante cadastrado com sucesso!");
                    listarFabricante();
                    limparCampos();
                    txtFabricante.requestFocus();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Erro: Fabricante não cadastrado.");
                    txtFabricante.requestFocus();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Fabricante já cadastrado!");
                limparCampos();
                txtFabricante.requestFocus();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Preencha o campo fabricante.");
            txtFabricante.requestFocus();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int linha = getLinhaTable();
        if(linha > -1){
            int idFabricante = Integer.parseInt(getValorLinhaTable(linha, 0));
            String nomeFabricanteTabela = getValorLinhaTable(linha, 1);
            String fabricanterTxt = txtFabricante.getText().toUpperCase();
            if(!nomeFabricanteTabela.equals(fabricanterTxt)){//verificação para poder liberar a alteração.
                Fabricante fabricante = new Fabricante();
                fabricante.setNome(txtFabricante.getText().toUpperCase());
                FabricanteDao fd = new FabricanteDao();
                boolean alterar = fd.alterar(fabricante, idFabricante);
                if(alterar == true){
                    fd.alterar(fabricante, idFabricante);
                    listarFabricante();
                    limparCampos();
                    JOptionPane.showMessageDialog(null, "Fabricante alterado com sucesso.");
                    btnSalvar.setEnabled(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Erro ao alterar fabricante.");
                    limparCampos();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Digite um fabricante diferente para poder alterar um já existente.");
                txtFabricante.requestFocus();
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linha = getLinhaTable();
        if(linha > -1){
            int idFabricante = Integer.parseInt(getValorLinhaTable(linha, 0));
            String fabricanteTabela = getValorLinhaTable(linha, 1);
            String nomeFabricante = txtFabricante.getText();
            if(fabricanteTabela.equals(nomeFabricante)){
                FabricanteDao fd = new FabricanteDao();
                boolean excluir = fd.excluir(idFabricante);
                if(excluir == true){
                    JOptionPane.showMessageDialog(null, "Fabricante excluído com sucesso.");
                    listarFabricante();
                    limparCampos();
                    btnSalvar.setEnabled(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Erro ao excluir fabricante.");
                    txtFabricante.requestFocus();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "O campo fabricante e o fabricante da tabela devem estar iguais \n para realizar a exclusão.");
                limparCampos();
                txtFabricante.requestFocus();
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

        public void listarFabricante(){
            FabricanteDao fd = new FabricanteDao();
        List<Fabricante>lista = fd.listarFabricante();
        
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        
        model.setNumRows(0);
        
        for(Fabricante fabricante: fd.listarFabricante()){
            model.addRow(new Object[]{
                fabricante.getIdFabricante(),
                fabricante.getNome()
            });
        }
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    
    public Integer getLinhaTable(){
        int linha = tabela.getSelectedRow();
        return linha;
    }
    
    public String getValorLinhaTable(int linha, int coluna){
        String valorLinhaTable = tabela.getModel().getValueAt(linha, coluna).toString();
        return valorLinhaTable;
    }
    
    public void limparCampos(){
        txtFabricante.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaFabricante dialog = new TelaFabricante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtFabricante;
    // End of variables declaration//GEN-END:variables
}
