/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.Icones;

import Dao.CartuchoDao;
import controller.Cartucho;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author israe
 */
public class TelaCartucho extends javax.swing.JDialog {

    /**
     * Creates new form TelaCartucho
     */
    public TelaCartucho(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarComboBoxImpressora();
        listarCartuchos();
        desabilitarCampos();
        desabilitarBotoes();
        this.tabelaAlterarCartuchoTeste = new TelaTableAlterarCartucho(parent, rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCartuchos = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtModelo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxImpressora = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboBoxSetor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        radioBuscar = new javax.swing.JRadioButton();
        labelVoltar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        giroQuantidade = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        txtCor = new javax.swing.JComboBox<>();
        txtTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Cartuchos");

        tabelaCartuchos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabelaCartuchos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "MODELO", "TIPO", "IMPRESSORA", "SETOR IMPRESSORA", "COR", "QUANTIDADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCartuchos.setToolTipText("");
        jScrollPane1.setViewportView(tabelaCartuchos);

        btnNovo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Clique aqui para cadastrar um novo cartucho");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Clique aqui para sallvar operações iniciadas");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("Clique aqui para alterar um item.");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtModelo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtModelo.setToolTipText("Digite o modelo do cartucho");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Modelo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tipo");

        comboBoxImpressora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxImpressora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Impressora" }));
        comboBoxImpressora.setToolTipText("Selecione a impressora");
        comboBoxImpressora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxImpressora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxImpressoraActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Impressora");

        comboBoxSetor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Setor" }));
        comboBoxSetor.setToolTipText("Selecione o setor");
        comboBoxSetor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Setor Impressora");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Quantidade");

        txtBusca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBusca.setToolTipText("Buscar palavra digitada");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/magnifier.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setMaximumSize(new java.awt.Dimension(91, 35));
        btnBuscar.setMinimumSize(new java.awt.Dimension(91, 35));
        btnBuscar.setPreferredSize(new java.awt.Dimension(91, 34));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        radioBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioBuscar.setText("Buscar todos");
        radioBuscar.setToolTipText("Ative para mostrar todas as impressoras");
        radioBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/Logout_37127.png"))); // NOI18N
        labelVoltar.setToolTipText("Voltar");
        labelVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelVoltar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                labelVoltarAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        labelVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelVoltarMouseClicked(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar Operação");
        btnCancelar.setToolTipText("Clique aqui para cancelar a operação iniciada");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        giroQuantidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        giroQuantidade.setToolTipText("Para alterar a quantidade em estoque, use o módulo de Gerenciamento de Estoque de Cartuchos");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cor");

        txtCor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRETO", "AMARELO", "AZUL", "VERMELHO" }));

        txtTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TONER", "TINTA", "CARTUCHO" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(comboBoxImpressora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBusca)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboBoxSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(radioBuscar)
                                                .addGap(37, 37, 37))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(33, 33, 33)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(txtCor, 0, 185, Short.MAX_VALUE)))))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(294, 294, 294)
                                .addComponent(giroQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelVoltar)
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBoxImpressora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(giroQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelVoltar))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusca))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtBusca.getAccessibleContext().setAccessibleName("");
        btnBuscar.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private TelaTableAlterarCartucho tabelaAlterarCartuchoTeste;
    private Integer idCartucho;
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void comboBoxImpressoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxImpressoraActionPerformed
        if(!comboBoxImpressora.getSelectedItem().equals("Impressora")){
            comboBoxSetor.removeAllItems();
            CartuchoDao cd = new CartuchoDao();
            String impressora = (String) comboBoxImpressora.getSelectedItem();
            int idImpressora = cd.getIdJcomboBoxImpressora(impressora);
            int idSetor = cd.getIdSetorImpressora(idImpressora);
            String setor = cd.getSetorCartucho(idSetor);
            comboBoxSetor.addItem(setor);
            comboBoxSetor.setSelectedItem(setor);
        }else{
            comboBoxSetor.removeAllItems();
            comboBoxSetor.addItem("Setor");
            comboBoxSetor.setSelectedItem("Setor");
        }

    }//GEN-LAST:event_comboBoxImpressoraActionPerformed

    private void labelVoltarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_labelVoltarAncestorAdded
        //
    }//GEN-LAST:event_labelVoltarAncestorAdded

    private void labelVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVoltarMouseClicked
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_labelVoltarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        desabilitarBotoes();
        desabilitarCampos();
        limparCampos();
        btnNovo.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        habilitarCampos();
        btnNovo.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
    }//GEN-LAST:event_btnNovoActionPerformed
       
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //Verificando se o botão alterar está desabilitado.
        if(!btnAlterar.isEnabled()){
            if(txtModelo.getText().equals("") || txtTipo.getSelectedItem().equals("") || txtCor.getSelectedItem().equals("") ||
               comboBoxImpressora.getSelectedItem().equals("Impressora") || comboBoxSetor.getSelectedItem().equals("Setor")){
                JOptionPane.showMessageDialog(null, "Preecha todos os campos.");            
            }
            else
            {
                String modelo = txtModelo.getText().toUpperCase();
                String tipo = txtTipo.getSelectedItem().toString();
                int quantidade = (int) giroQuantidade.getValue();
                String cor = txtCor.getSelectedItem().toString();
                String impressora = comboBoxImpressora.getSelectedItem().toString();
                
                CartuchoDao cd = new CartuchoDao();
                
                int idImpressora = cd.getIdJcomboBoxImpressora(impressora);
                
                Cartucho cartucho = new Cartucho();
                cartucho.setCor(cor);
                cartucho.setImpressora(idImpressora);
                cartucho.setModelo(modelo);
                cartucho.setQuantidade(quantidade);
                cartucho.setTipo(tipo);
                
                if(cd.salvar(cartucho)){
                    JOptionPane.showMessageDialog(null, "Cartucho incluído com sucesso.");
                    listarCartuchos();
                    limparCampos();
                    desabilitarCampos();
                    desabilitarBotoes();
                    btnNovo.setEnabled(true);
                    btnAlterar.setEnabled(true);
                    btnExcluir.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao inserir cartucho.");
                }
            }
        }
        else{
            //Com o botão alterar desabilitado segue o código abaixo:
            if(txtModelo.getText().equals("") || txtTipo.getSelectedItem().equals("") || txtCor.getSelectedItem().equals("") ||
               comboBoxImpressora.getSelectedItem().equals("Impressora") || comboBoxSetor.getSelectedItem().equals("Setor")){
               JOptionPane.showMessageDialog(null, "Preecha todos os campos.");            
            }
            else
            {
                String modelo = txtModelo.getText().toUpperCase();
                String tipo = txtTipo.getSelectedItem().toString();
                String cor = txtCor.getSelectedItem().toString();
                String impressora = comboBoxImpressora.getSelectedItem().toString();
                
                CartuchoDao cd = new CartuchoDao();
                
                int idImpressora = cd.getIdJcomboBoxImpressora(impressora);
                
                Cartucho cartucho = new Cartucho();
                cartucho.setCor(cor);
                cartucho.setImpressora(idImpressora);
                cartucho.setModelo(modelo);
                cartucho.setTipo(tipo);
                
                if(cd.editar(cartucho,idCartucho)){
                    JOptionPane.showMessageDialog(null, "Cartucho alterado com sucesso.");
                    listarCartuchos();
                    limparCampos();
                    desabilitarCampos();
                    desabilitarBotoes();
                    btnNovo.setEnabled(true);
                    //btnAlterar.setEnabled(true);
                    btnExcluir.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(null, "Erro ao inserir cartucho.");
                }
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        //Passando dados da tabela da TelaTableAlterarCartucho para a tela Cartucho.
        this.tabelaAlterarCartuchoTeste.setVisible(true);
        
        this.idCartucho = Integer.parseInt(tabelaAlterarCartuchoTeste.getIdCartucho());
        this.txtTipo.setSelectedItem(String.valueOf(tabelaAlterarCartuchoTeste.getTipo()));
        this.txtModelo.setText(String.valueOf(tabelaAlterarCartuchoTeste.getModelo()));
        this.comboBoxImpressora.setSelectedItem(String.valueOf(tabelaAlterarCartuchoTeste.getImpressora()));
        this.txtCor.setSelectedItem(String.valueOf(tabelaAlterarCartuchoTeste.getCor()));
        this.giroQuantidade.setValue(Integer.valueOf(tabelaAlterarCartuchoTeste.getQuantidade()));
        
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        habilitarCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    public void carregarComboBoxImpressora(){
        CartuchoDao cd = new CartuchoDao();
        cd.carregarJcomboBox(comboBoxImpressora);
    }
    
    public void desabilitarCampos(){
        txtModelo.setEnabled(false);
        giroQuantidade.setEnabled(false);
        txtTipo.setEnabled(false);
        txtCor.setEnabled(false);
        comboBoxImpressora.setEnabled(false);
        comboBoxSetor.setEnabled(false);
    }
    
    public void desabilitarBotoes(){
        btnSalvar.setEnabled(false);
        /*btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);*/
        btnCancelar.setEnabled(false);
    }
    
    public void habilitarCampos(){
        txtModelo.setEnabled(true);
        //giroQuantidade.setEnabled(true);
        txtTipo.setEnabled(true);
        txtCor.setEnabled(true);
        comboBoxImpressora.setEnabled(true);
        comboBoxSetor.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }
    
    public void limparCampos(){
        txtModelo.setText("");
        giroQuantidade.setValue(0);
        txtTipo.setSelectedItem("TONER");
        txtCor.setSelectedItem("PRETO");
        comboBoxImpressora.setSelectedItem("Impressora");
        comboBoxSetor.removeAllItems();
        comboBoxSetor.addItem("Setor");
        comboBoxSetor.setSelectedItem("Setor");
    }
    
    public void listarCartuchos (){
        
        CartuchoDao cd = new CartuchoDao();
        
        List<Cartucho> listarCartucho = cd.selectCartucho();
           
        DefaultTableModel modelo = (DefaultTableModel) tabelaCartuchos.getModel();
        
        //Para a tabela não definir a largura das colunas de forma automática.
        tabelaCartuchos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        modelo.setNumRows(0);
        
        for (Cartucho c : cd.selectCartucho()) {

            modelo.addRow(new Object[]{
                c.getIdCartucho(),
                c.getModelo(),
                c.getTipo(),
                c.getModeloImpressora(),
                c.getSetor(),
                c.getCor(),
                c.getQuantidade()
            });

        }
        
        //Definindo a largura das colunas da tabela tabelaCartuchos.
        
        tabelaCartuchos.getColumnModel().getColumn(0).setPreferredWidth(70);
        tabelaCartuchos.getColumnModel().getColumn(1).setPreferredWidth(140);
        tabelaCartuchos.getColumnModel().getColumn(2).setPreferredWidth(130);
        tabelaCartuchos.getColumnModel().getColumn(3).setPreferredWidth(190);
        tabelaCartuchos.getColumnModel().getColumn(4).setPreferredWidth(175);
        tabelaCartuchos.getColumnModel().getColumn(5).setPreferredWidth(120);
        tabelaCartuchos.getColumnModel().getColumn(6).setPreferredWidth(102);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCartucho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCartucho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCartucho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCartucho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCartucho dialog = new TelaCartucho(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> comboBoxImpressora;
    private javax.swing.JComboBox<String> comboBoxSetor;
    private javax.swing.JSpinner giroQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelVoltar;
    private javax.swing.JRadioButton radioBuscar;
    private javax.swing.JTable tabelaCartuchos;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JComboBox<String> txtCor;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JComboBox<String> txtTipo;
    // End of variables declaration//GEN-END:variables
}
