/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.Icones;

import Dao.ImpressoraDao;
import Dao.UsuarioDao;
import controller.Impressora;
import controller.ImpressoraTableModel;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author israe
 */
public class TelaImpressora2 extends javax.swing.JDialog {

    /**
     * Creates new form TelaImpressora2
     */
    
    private String busca;
    
    public String getBusca(){
        return this.busca;
    }
    
    public void setBusca(String busca){
        this.busca = busca;
    }
    
    private Date data = new Date();

    public Date getData() {
        return data;
    }

    public void setData(Date data) {
        this.data = data;
    }
    
    //ImpressoraTableModel tableModel = new ImpressoraTableModel();
    
    public TelaImpressora2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JComboBoxFabricante();
        JComboBoxSetor();
        desabilitarCamposInicias();
        //jrbTodos.setSelected(true);
        receberUsuarioLogado();
        //jTableImpressora.setModel(tableModel);//É nessa linha que os nomes das colunas são resgatadas do modelo, para a tabela.
        //listarImpressora();
        btnBuscar.requestFocus(true);
        //this.tabelaTelaImpressora = new TelaTableAlterarImpressora(parent, rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelModelo = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxFabricante = new javax.swing.JComboBox<>();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxSetor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnInserirPaginas = new javax.swing.JButton();
        btnRelPagImpressas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableImpressora = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jrbTodos = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInserirPaginas = new javax.swing.JMenu();
        menuRelatorioPaginas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de impressoras");
        setPreferredSize(new java.awt.Dimension(915, 679));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Campos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabelModelo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelModelo.setText("Modelo");

        txtSerie.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSerie.setToolTipText("Digite a série da impressora");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Serie");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Fabricante");

        jComboBoxFabricante.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxFabricante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fabricante" }));
        jComboBoxFabricante.setToolTipText("selecione o fabricante da impressora");
        jComboBoxFabricante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFabricanteActionPerformed(evt);
            }
        });

        txtModelo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtModelo.setToolTipText("Digite o modelo da impressora");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Setor");

        jComboBoxSetor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBoxSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Setor" }));
        jComboBoxSetor.setToolTipText("Selecione o setor que a impressora encontra-se");
        jComboBoxSetor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSetorActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/Logout_37127.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelModelo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtSerie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                        .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxSetor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxFabricante, 0, 362, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModelo)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botões", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Clique aqui para sallvar operações iniciadas");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("Clique aqui para alterar uma impressora");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Clique aqui para incluir uma nova impressora");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Clique aqui para excluir uma impressora");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Clique aqui para cancelar uma operação iniciada");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnInserirPaginas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnInserirPaginas.setText("pág. impressas");
        btnInserirPaginas.setToolTipText("Clique para inserir relatório de pág. impressas");
        btnInserirPaginas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInserirPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirPaginasActionPerformed(evt);
            }
        });

        btnRelPagImpressas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnRelPagImpressas.setText("Relatório");
        btnRelPagImpressas.setToolTipText("Clique aqui para emitir relatório de pág. impressas");
        btnRelPagImpressas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelPagImpressas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelPagImpressasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelPagImpressas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInserirPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserirPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelPagImpressas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(950, 700));

        jTableImpressora.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTableImpressora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MODELO", "SERIE", "FABRICANTE", "SETOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableImpressora.setToolTipText("Informação rápida sobre as impressoras cadastradas");
        jTableImpressora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableImpressoraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableImpressora);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        txtBusca.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/magnifier.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarKeyPressed(evt);
            }
        });

        jrbTodos.setSelected(true);
        jrbTodos.setText("Buscar Todos");
        jrbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbTodos)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jrbTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        menuInserirPaginas.setText("Inserir páginas Impressas");
        menuInserirPaginas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuInserirPaginas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuInserirPaginas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInserirPaginasMouseClicked(evt);
            }
        });
        menuInserirPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInserirPaginasActionPerformed(evt);
            }
        });
        menuInserirPaginas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                menuInserirPaginasKeyPressed(evt);
            }
        });
        jMenuBar1.add(menuInserirPaginas);

        menuRelatorioPaginas.setText("Relatório de páginas impressas");
        menuRelatorioPaginas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuRelatorioPaginas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuRelatorioPaginas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRelatorioPaginasMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRelatorioPaginas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private TelaTableAlterarImpressora tabelaTelaImpressora;
    private Integer idImpressora;
    
    public void receberUsuarioLogado(){
        UsuarioDao ud = new UsuarioDao();
        String usuario = ud.getUsuarioLogado();
        int idUsuarioLogado = ud.getIdUsuarioLogado(usuario);
        String adm = ud.verSeUsuarioEadm(idUsuarioLogado);
        
        if(adm.equals("nao")){
            menuInserirPaginas.setEnabled(false);   
            menuRelatorioPaginas.setEnabled(false);
            btnSalvar.setEnabled(false);   
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnNovo.setEnabled(false);
        } 
    }
   
    public void desabilitarCamposInicias(){
        txtModelo.setEnabled(false);
        txtSerie.setEnabled(false);
        jComboBoxFabricante.setEnabled(false);
        jComboBoxSetor.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }
    
    public void habilitarCampos(){
        txtModelo.setEnabled(true);
        txtSerie.setEnabled(true);
        jComboBoxFabricante.setEnabled(true);
        jComboBoxSetor.setEnabled(true);
        btnCancelar.setEnabled(true);
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //Verificando se o botão alterar está desabilitado.
        if(!btnAlterar.isEnabled() && !btnExcluir.isEnabled()){
            if(txtModelo.getText().equals("") || txtSerie.getText().equals("") || jComboBoxFabricante.getSelectedItem().equals("Fabricante")
            || jComboBoxSetor.getSelectedItem().equals("")){
                JOptionPane.showMessageDialog(null, "Preecha todos os campos.".toUpperCase());
            }
            else{
                ImpressoraDao impDao = new ImpressoraDao();
                
                String serie = txtSerie.getText().toUpperCase();
                
                if(impDao.verSeImpressoraEstaCadastrada(serie) == true){
                    String fabricante = jComboBoxFabricante.getSelectedItem().toString().toUpperCase();

                    Integer idFabricante = impDao.getIdFabricanteJcomboBox(fabricante);

                    String setor = jComboBoxSetor.getSelectedItem().toString().toUpperCase();

                    Integer idSetor = impDao.getIdSetorJComboBox(setor);

                    Impressora impressora = new Impressora();

                    impressora.setModelo(txtModelo.getText().toUpperCase());
                    impressora.setSerie(txtSerie.getText().toUpperCase());
                    impressora.setId_fabricante(idFabricante);
                    impressora.setId_setor(idSetor);

                    if(impDao.salvar(impressora) == true){
                        JOptionPane.showMessageDialog(null, "Impressora salva com sucesso!".toUpperCase());
                        desabilitarCamposInicias();
                        btnNovo.setEnabled(true);
                        btnAlterar.setEnabled(true);
                        btnExcluir.setEnabled(true);
                        limparCampos();
                        listarImpressora();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Erro ao cadastrar nova impressora.".toUpperCase());
                        limparCampos();
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Esta impressora já está cadastrada.".toUpperCase());
                    txtSerie.requestFocus(true);
                }
            }
        }//Verificando se o botão alterar está habilitado e o botão excluir desabilitado.
        else if(btnAlterar.isEnabled()==true && btnExcluir.isEnabled()==false){
            if(txtModelo.getText().equals("") || txtSerie.getText().equals("") || jComboBoxFabricante.getSelectedItem().equals("Fabricante")
            || jComboBoxSetor.getSelectedItem().equals("")){
                JOptionPane.showMessageDialog(null, "Preecha todos os campos.".toUpperCase());
            }
            else{
                String fabricante = jComboBoxFabricante.getSelectedItem().toString();
                String setor = jComboBoxSetor.getSelectedItem().toString();
                
                ImpressoraDao impDao = new ImpressoraDao();
                
                int idFabricante = impDao.getIdFabricanteJcomboBox(fabricante);
                int idSetor = impDao.getIdSetorJComboBox(setor);
                
                Impressora imp = new Impressora();
                
                imp.setId_impressora(this.idImpressora);
                imp.setModelo(txtModelo.getText());
                imp.setSerie(txtSerie.getText());
                imp.setId_fabricante(idFabricante);
                imp.setId_setor(idSetor);
                
                if(impDao.editar(imp, idImpressora) == true){
                    JOptionPane.showMessageDialog(null, "Impressora alterada com sucesso.");
                    desabilitarCamposInicias();
                    btnNovo.setEnabled(true);
                    btnAlterar.setEnabled(true);
                    btnExcluir.setEnabled(true);
                    limparCampos();
                    listarImpressora();
                    clearItensTableAlterarImpressora();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Erro ao alterar impressora");
                    limparCampos();
                }
            }
        }//Verificando se o botão excluir está habilitado e o botão alterar desabilitado.
        
        else{
            JOptionPane.showMessageDialog(null, "Feche esta janela e tente realizar a operação mais uma vez.".toUpperCase());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        btnNovo.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        //método para chamar a tela TableAlterarCartucho.
        //teste para atualizar tabela TableAlterar Cartucho.
        //this.tabelaTelaImpressora.listarImpressora();
        //getItensTableAlterarImpressora();
        
        int linha = jTableImpressora.getSelectedRow();
        
        if(linha > -1 && coletaDadosTabela == true){
            this.idImpressora = (int) jTableImpressora.getModel().getValueAt(linha, 0);
            
            if(btnExcluir.isEnabled()==true && btnAlterar.isEnabled()==false){
                Impressora imp = new Impressora();

                int teste = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o item selecionado?", "Confirmar exclusão", JOptionPane.YES_NO_OPTION);

                if(teste == JOptionPane.YES_OPTION){
                    ImpressoraDao impDao = new ImpressoraDao();
                    if(impDao.excluir(idImpressora) == true){
                        JOptionPane.showMessageDialog(null, "Operação realizada.", "Exclusão confirmada", JOptionPane.INFORMATION_MESSAGE);
                        listarImpressora();
                        limparCampos();
                        desabilitarCamposInicias();
                        btnNovo.setEnabled(true);
                        btnAlterar.setEnabled(true);
                        btnExcluir.setEnabled(true);
                        btnCancelar.setEnabled(false);
                        clearItensTableAlterarImpressora();
                    }
                }
                else if (teste == JOptionPane.NO_OPTION)
                {
                    JOptionPane.showMessageDialog(null, "Operação não realizada.", "Exclusão cancelada", JOptionPane.INFORMATION_MESSAGE);
                    btnCancelar.setEnabled(false);
                    btnAlterar.setEnabled(true);
                    btnSalvar.setEnabled(false);
                    btnNovo.setEnabled(true);
                    coletaDadosTabela = false;
                    limparCampos();
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Escolha um item da lista, com dois cliques, para excluí-lo.".toUpperCase());
            btnCancelar.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnNovo.setEnabled(true);
            btnAlterar.setEnabled(true);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
        
    public void getItensTableAlterarImpressora(){
        this.tabelaTelaImpressora.setVisible(true);
        
        this.idImpressora = Integer.parseInt(tabelaTelaImpressora.getIdImpressora());
        this.txtModelo.setText(String.valueOf(tabelaTelaImpressora.getModeloImpressora()));
        this.txtSerie.setText(String.valueOf(tabelaTelaImpressora.getSerieImpressora()));
        this.jComboBoxFabricante.setSelectedItem(String.valueOf(tabelaTelaImpressora.getFabImpressora()));
        this.jComboBoxSetor.setSelectedItem(String.valueOf(tabelaTelaImpressora.getSetorImpressora()));
    }
    
    public void clearItensTableAlterarImpressora(){
        tabelaTelaImpressora.setImpModelo("");
        tabelaTelaImpressora.setImpSerie("");
        tabelaTelaImpressora.setImpFabricante("");
        tabelaTelaImpressora.setImpSetor("");
    }
    
    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);

        int linha = jTableImpressora.getSelectedRow();

        if(linha > -1 && coletaDadosTabela == true){
            habilitarCampos();
            this.idImpressora = (Integer)jTableImpressora.getModel().getValueAt(linha, 0);
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um item na tabela, com dois cliques, abaixo para alterá-lo".toUpperCase());
            btnCancelar.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnNovo.setEnabled(true);
            btnExcluir.setEnabled(true);
        } 
    }//GEN-LAST:event_btnAlterarActionPerformed

    boolean coletaDadosTabela = false; 
    
    private void jTableImpressoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableImpressoraMouseClicked
        if(evt.getClickCount() == 2){
            int linha = jTableImpressora.getSelectedRow();
            
            if(linha > -1){
                this.idImpressora = (int) jTableImpressora.getModel().getValueAt(linha, 0);
                String modeloImpressora = jTableImpressora.getModel().getValueAt(linha, 1).toString();
                String serie = jTableImpressora.getModel().getValueAt(linha, 2).toString();
                String fabricante = jTableImpressora.getModel().getValueAt(linha, 3).toString();
                String setor = jTableImpressora.getModel().getValueAt(linha, 4).toString();
                
                txtModelo.setText(modeloImpressora);
                txtSerie.setText(serie);
                jComboBoxFabricante.setSelectedItem(fabricante);
                jComboBoxSetor.setSelectedItem(setor);
                this.coletaDadosTabela = true;
            }
            else{
                JOptionPane.showMessageDialog(null, "Selecione uma impressora para prosseguir!".toUpperCase());
            }
        }
        else if(evt.getButton() == 3){
            jTableImpressora.getSelectionModel().clearSelection();
            limparCampos();
            this.coletaDadosTabela = false;
        }
    
    }//GEN-LAST:event_jTableImpressoraMouseClicked
    
    public void listarImpressora(){
        ImpressoraDao impDao = new ImpressoraDao();
        
        List<Impressora> listaImpressoras = impDao.selectImpressora();
        
        DefaultTableModel model = (DefaultTableModel) jTableImpressora.getModel();
        
        model.setNumRows(0);
        
        for(Impressora impressora: impDao.selectImpressora()){
            
            model.addRow(new Object[]{
                impressora.getId_impressora(),
                impressora.getModelo(),
                impressora.getSerie(),
                impressora.getFabricante(),
                impressora.getSetor()
            });
            
        jTableImpressora.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableImpressora.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTableImpressora.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableImpressora.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTableImpressora.getColumnModel().getColumn(4).setPreferredWidth(160);
        
        }
        
    }
    
    public void listarImpressoraLike(String busca){
        
        busca = this.busca;
        
        ImpressoraDao impDao = new ImpressoraDao();
        
        List<Impressora> listaImpressoras = impDao.listaImpressoraLike(busca);
        
        DefaultTableModel model = (DefaultTableModel) jTableImpressora.getModel();
        
        model.setNumRows(0);
        
        for(Impressora impressora: impDao.listaImpressoraLike(busca)){
            
            model.addRow(new Object[]{
                
                impressora.getId_impressora(),
                impressora.getModelo(),
                impressora.getSerie(),
                impressora.getFabricante(),
                impressora.getSetor()
            });
            
        jTableImpressora.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTableImpressora.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTableImpressora.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableImpressora.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTableImpressora.getColumnModel().getColumn(4).setPreferredWidth(150);
        
        }
        
    }
    
    public void limparCampos(){
        txtModelo.setText("");
        txtSerie.setText("");
        jComboBoxFabricante.setSelectedItem("Fabricante");
        jComboBoxSetor.setSelectedItem("Setor");
    }
    
    private void jComboBoxFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFabricanteActionPerformed

    private void jComboBoxSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSetorActionPerformed

    private void menuInserirPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInserirPaginasActionPerformed
//
    }//GEN-LAST:event_menuInserirPaginasActionPerformed

    private void menuInserirPaginasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuInserirPaginasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuInserirPaginasKeyPressed

    private void menuInserirPaginasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInserirPaginasMouseClicked
        TelaControlePaginas controlePaginas = new TelaControlePaginas(null, rootPaneCheckingEnabled);
        controlePaginas.setVisible(true);
    }//GEN-LAST:event_menuInserirPaginasMouseClicked

    private void menuRelatorioPaginasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRelatorioPaginasMouseClicked
        TelaControlPaginasRel telaRelatorioPaginas = new TelaControlPaginasRel(null, rootPaneCheckingEnabled);
        telaRelatorioPaginas.setVisible(true);
    }//GEN-LAST:event_menuRelatorioPaginasMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnInserirPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirPaginasActionPerformed
        TelaControlePaginas tela = new TelaControlePaginas(null, rootPaneCheckingEnabled);
        tela.setVisible(true);
    }//GEN-LAST:event_btnInserirPaginasActionPerformed

    private void btnRelPagImpressasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelPagImpressasActionPerformed
        TelaControlPaginasRel tela = new TelaControlPaginasRel(null, rootPaneCheckingEnabled);
        tela.setVisible(true);
    }//GEN-LAST:event_btnRelPagImpressasActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        habilitarCampos();
        limparCampos();
        this.idImpressora = null;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtModelo.setEnabled(false);
        txtSerie.setEnabled(false);
        jComboBoxFabricante.setEnabled(false);
        jComboBoxSetor.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnNovo.setEnabled(true);
        limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.busca = this.txtBusca.getText().toUpperCase();
        
            if(jrbTodos.isSelected() == true){
                listarImpressora();
                txtBusca.requestFocus(true);
            }
            else
            {
                if(jrbTodos.isSelected()== false && !this.busca.equals("")){
                    listarImpressoraLike(busca);
                    txtBusca.setText("");
                    txtBusca.requestFocus(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Digite um termo para poder buscá-lo");
                    txtBusca.requestFocus(true);
                }
            }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.busca = this.txtBusca.getText().toUpperCase();

            if(jrbTodos.isSelected() == true){
                listarImpressora();
                txtBusca.requestFocus(true);
            }
            else
            {
                if(jrbTodos.isSelected() == false && !this.busca.equals("")){
                    listarImpressoraLike(busca);
                    txtBusca.setText("");
                    txtBusca.requestFocus(true);
                }
            }
        }
    }//GEN-LAST:event_btnBuscarKeyPressed

    private void jrbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTodosActionPerformed
        if(jrbTodos.isSelected()== true){
            btnBuscar.requestFocus(true);
        }else if(jrbTodos.isSelected()== false){
            txtBusca.requestFocus(true);
        }
    }//GEN-LAST:event_jrbTodosActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        
        if(!txtBusca.getText().equals("") && jrbTodos.isSelected()==false){
            btnBuscar.requestFocus(true);
        }
        else if(txtBusca.getText().equals("") && jrbTodos.isSelected()==true){
            btnBuscar.requestFocus(true);
        }else{
            JOptionPane.showMessageDialog(null, "Digite um termo para pesquisa.");
        }
    }//GEN-LAST:event_txtBuscaActionPerformed

    public void JComboBoxFabricante(){
        ImpressoraDao impDao = new ImpressoraDao();
        impDao.carregarJcomboBoxFabricante(jComboBoxFabricante);
    }
    
    public void JComboBoxSetor(){
        ImpressoraDao impDao = new ImpressoraDao();
        impDao.carregarJComboBoxSetor(jComboBoxSetor);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaImpressora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaImpressora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaImpressora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaImpressora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaImpressora2 dialog = new TelaImpressora2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserirPaginas;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRelPagImpressas;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> jComboBoxFabricante;
    private javax.swing.JComboBox<String> jComboBoxSetor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableImpressora;
    private javax.swing.JRadioButton jrbTodos;
    private javax.swing.JMenu menuInserirPaginas;
    private javax.swing.JMenu menuRelatorioPaginas;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtSerie;
    // End of variables declaration//GEN-END:variables
}
