/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas.Icones;

import Dao.ControleUsuarioDao;
import Dao.UsuarioDao;
import controller.ControleDeUsuario;
import controller.Usuario;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HJP_TI-CPD2
 */
public class TelaControleUsuario extends javax.swing.JDialog {

    /**
     * Creates new form TelaControleUsuario
     */
    public TelaControleUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        checkAdm = new javax.swing.JCheckBox();
        checkAtivo = new javax.swing.JCheckBox();
        checkInserirCartuchio = new javax.swing.JCheckBox();
        checkAlterarCartucho = new javax.swing.JCheckBox();
        checkRemoverCartucho = new javax.swing.JCheckBox();
        checkImpriRelCartuchos = new javax.swing.JCheckBox();
        checkInserirImpr = new javax.swing.JCheckBox();
        checkAlterarImpr = new javax.swing.JCheckBox();
        checkRemoverImpr = new javax.swing.JCheckBox();
        checkImprimirRelImpr = new javax.swing.JCheckBox();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Usuários");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOME", "LOGIN", "ADM", "ATIVO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("Clique com botão direito do mouse para desmarcar uma linha.");
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        checkAdm.setText("ADM");

        checkAtivo.setText("ATIVO");

        checkInserirCartuchio.setText("INSERIR CARTUCHOS");

        checkAlterarCartucho.setText("ALTERAR CARTUCHOS");

        checkRemoverCartucho.setText("REMOVER CARTUCHOS");

        checkImpriRelCartuchos.setText("IMPRIMIR REL. CARTUCHOS");

        checkInserirImpr.setText("INSERIR IMPR.");

        checkAlterarImpr.setText("ALTERAR IMPR.");

        checkRemoverImpr.setText("REMOVER IMPR.");

        checkImprimirRelImpr.setText("IMPRIMIR REL. IMPR.");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuário:");

        jLabel2.setText("Login:");

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        jLabel3.setText("Senha:");

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        btnSalvar.setText("CADASTRAR");
        btnSalvar.setPreferredSize(new java.awt.Dimension(81, 23));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        btnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarKeyPressed(evt);
            }
        });

        btnAlterar.setText("ALTERAR");
        btnAlterar.setPreferredSize(new java.awt.Dimension(81, 23));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        btnAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAlterarKeyPressed(evt);
            }
        });

        btnRemover.setText("REMOVER");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Icones/icones/KeyChainAccess_37052.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkAdm)
                            .addComponent(checkAtivo))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkInserirCartuchio)
                            .addComponent(checkAlterarCartucho))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkRemoverCartucho)
                            .addComponent(checkImpriRelCartuchos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkImprimirRelImpr)
                            .addComponent(checkRemoverImpr))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkAlterarImpr)
                            .addComponent(checkInserirImpr))
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(checkAdm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkAtivo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(checkInserirCartuchio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkAlterarCartucho))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(checkRemoverCartucho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkImpriRelCartuchos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(checkRemoverImpr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkImprimirRelImpr))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(checkInserirImpr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkAlterarImpr)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //funcionando a verificação de dois cliques.
        if(evt.getClickCount()== 2){
            btnSalvar.setEnabled(false);
            int linha = getLinhaTable();
            
            String idUsuario = getValorLinhaTable(linha, 0);
            int idUsuarioInt = Integer.parseInt(idUsuario);
            ControleUsuarioDao usd = new ControleUsuarioDao();
            txtSenha.setText(usd.getPasswordUsuario(idUsuarioInt));
            txtUsuario.setText(getValorLinhaTable(linha, 1));
            txtLogin.setText(getValorLinhaTable(linha, 2));
            
            if(getValorLinhaTable(linha, 4).equals("sim")){
                checkAtivo.setSelected(true);
            }else{
                checkAtivo.setSelected(false);
            }
            
            if(getValorLinhaTable(linha, 3).equals("sim")){
                checkAdm.setSelected(true);
            }else{
                checkAdm.setSelected(false);
            }
            btnAlterar.requestFocus();
        }
        if(evt.getButton() == 3){
            int linha = getLinhaTable();
            if(linha > 0){
                jTable1.getSelectionModel().clearSelection();
                limparCampos();
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        ControleUsuarioDao cud = new ControleUsuarioDao();
        ControleDeUsuario cdu = new ControleDeUsuario();
        UsuarioDao ud = new UsuarioDao();
        Usuario usuario = new Usuario();

        //salvando usuario ao banco de Dados.
        usuario.setNome(txtUsuario.getText());
        usuario.setLogin(txtLogin.getText());
        usuario.setSenha(txtSenha.getText());

        boolean loginDisponivel = ud.loginDisponivel(txtLogin.getText());

        if(!txtUsuario.getText().equals("") && !txtLogin.getText().equals("") && !txtSenha.getText().equals("")){
            if(loginDisponivel == true){
                ud.salvarUsuario(usuario);
                JOptionPane.showMessageDialog(null, "Usuario cadastrado com sucesso!");

                //selecionando o usario cadastrado acima e salvando-o à tabela controledeusuario.
                String login = txtLogin.getText();
                int idUsuario = ud.getIdUsuario(login);
                System.out.println(idUsuario);
                String adm = checarCheck(checkAdm);
                String ativo = checarCheck(checkAtivo);

                cdu.setIdUsuario(idUsuario);
                cdu.setAdm(adm);
                cdu.setAtivo(ativo);

                if(cud.salvar(cdu)){
                    JOptionPane.showMessageDialog(null, "Usuario inserido à tabela controle de usuario.");
                }
                listarUsuarios();
            }
            else{
            JOptionPane.showMessageDialog(null, "Login já existe. Escolha um novo login.");
            txtLogin.setText("");
            txtLogin.requestFocus();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Prencha todos os campos!");
            txtUsuario.requestFocus();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
    //pegando dados da tabela.    
    int linha = getLinhaTable();
    
    if(linha < 0){
        JOptionPane.showMessageDialog(null, "Selecione um item para alterá-lo.");
    }
    else{
        String idUsuario = getValorLinhaTable(linha, 0).toString();
        int idUsuarioInt = Integer.parseInt(idUsuario);
        
        //pegando os dados dos campos de texto e checkBox.
        String txtUsuarioAlter = txtUsuario.getText();
        String txtLoginAlter = txtLogin.getText();
        String txtSenhaAlter = txtSenha.getText();
        String adm = checarCheck(checkAdm);
        String ativo = checarCheck(checkAtivo);

        Usuario usuario = new Usuario();
        UsuarioDao ud = new UsuarioDao();
        ControleUsuarioDao cdud = new ControleUsuarioDao();

        usuario.setNome(txtUsuarioAlter);
        usuario.setLogin(txtLoginAlter);
        usuario.setSenha(txtSenhaAlter);

        if(ud.alterar(usuario, idUsuarioInt) == true){

            ControleDeUsuario cdu = new ControleDeUsuario();
            cdu.setAdm(adm);
            cdu.setAtivo(ativo);
            
            //alterando se usuario é adm e ativo na tabela controledeusuario.
            cdud.alterar(idUsuarioInt, cdu);

            JOptionPane.showMessageDialog(null, "Usuario alterado com sucesso.");
            listarUsuarios();
            limparCampos();
        }
        else{
            JOptionPane.showMessageDialog(null, "Falha ao alterar usuário.");
            listarUsuarios();
            limparCampos();
        }
    }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        txtLogin.requestFocus();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        txtSenha.requestFocus();
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        btnSalvar.requestFocus();
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            ControleUsuarioDao cud = new ControleUsuarioDao();
            ControleDeUsuario cdu = new ControleDeUsuario();
            UsuarioDao ud = new UsuarioDao();
            Usuario usuario = new Usuario();

            //salvando usuario ao banco de Dados.
            usuario.setNome(txtUsuario.getText());
            usuario.setLogin(txtLogin.getText());
            usuario.setSenha(txtSenha.getText());

            boolean loginDisponivel = ud.loginDisponivel(txtLogin.getText());
            
            if(!txtUsuario.getText().equals("") && !txtLogin.getText().equals("") && !txtSenha.getText().equals("")){
                if(loginDisponivel == true){
                    ud.salvarUsuario(usuario);
                    JOptionPane.showMessageDialog(null, "Usuario cadastrado com sucesso!");

                    //selecionando o usario cadastrado acima e salvando-o à tabela controledeusuario.
                    String login = txtLogin.getText();
                    int idUsuario = ud.getIdUsuario(login);
                    System.out.println(idUsuario);
                    String adm = checarCheck(checkAdm);
                    String ativo = checarCheck(checkAtivo);

                    cdu.setIdUsuario(idUsuario);
                    cdu.setAdm(adm);
                    cdu.setAtivo(ativo);

                    if(cud.salvar(cdu)){
                        JOptionPane.showMessageDialog(null, "Usuario inserido à tabela controle de usuario.");
                    }
                    listarUsuarios();
                }
                else{
                JOptionPane.showMessageDialog(null, "Login já existe. Escolha um novo login.");
                txtLogin.setText("");
                txtLogin.requestFocus();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Prencha todos os campos!");
                txtUsuario.requestFocus();
            }
        }
    }//GEN-LAST:event_btnSalvarKeyPressed

    private void btnAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAlterarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //pegando dados da tabela.    
            int linha = getLinhaTable();

            if(linha < 0){
                JOptionPane.showMessageDialog(null, "Selecione um item para alterá-lo.");
            }
            else{
                String idUsuario = getValorLinhaTable(linha, 0).toString();
                int idUsuarioInt = Integer.parseInt(idUsuario);

                //pegando os dados dos campos de texto e checkBox.
                String txtUsuarioAlter = txtUsuario.getText();
                String txtLoginAlter = txtLogin.getText();
                String txtSenhaAlter = txtSenha.getText();
                String adm = checarCheck(checkAdm);
                String ativo = checarCheck(checkAtivo);

                Usuario usuario = new Usuario();
                UsuarioDao ud = new UsuarioDao();
                ControleUsuarioDao cdud = new ControleUsuarioDao();

                usuario.setNome(txtUsuarioAlter);
                usuario.setLogin(txtLoginAlter);
                usuario.setSenha(txtSenhaAlter);

                if(ud.alterar(usuario, idUsuarioInt) == true){

                    ControleDeUsuario cdu = new ControleDeUsuario();
                    cdu.setAdm(adm);
                    cdu.setAtivo(ativo);

                    //alterando se usuario é adm e ativo na tabela controledeusuario.
                    cdud.alterar(idUsuarioInt, cdu);

                    JOptionPane.showMessageDialog(null, "Usuario alterado com sucesso.");
                    listarUsuarios();
                    limparCampos();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Falha ao alterar usuário.");
                    listarUsuarios();
                    limparCampos();
                }
            }
        }
    }//GEN-LAST:event_btnAlterarKeyPressed

    public void limparCampos(){
        txtLogin.setText("");
        txtSenha.setText("");
        txtUsuario.setText("");
    }
    
    public String checarCheck(JCheckBox check){
        String resposta;
        if(check.isSelected()){
            resposta = "sim";
            return resposta;
        }else{
            resposta = "nao";
            return resposta;
        }
    }
    
    public Integer getLinhaTable(){
        
        int linhaSelecionada = jTable1.getSelectedRow();
        return linhaSelecionada;
    }
    
    public String getValorLinhaTable(Integer linha, Integer posicao){
        String valor = jTable1.getValueAt(linha, posicao).toString();
        return valor;
    }
    
    public void listarUsuarios(){
        
        ControleUsuarioDao cud = new ControleUsuarioDao();
        
        List<ControleDeUsuario> litaDeUsuarios = cud.listarUsuarios();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setNumRows(0);
        
        for(ControleDeUsuario cdu: cud.listarUsuarios()){
            model.addRow(new Object[]{
                cdu.getIdUsuario(),
                cdu.getNome(),
                cdu.getLogin(),
                cdu.getAdm(),
                cdu.getAtivo()
            });
        }
        
        //Definir espaçamendo de colunas.
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaControleUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaControleUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaControleUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaControleUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaControleUsuario dialog = new TelaControleUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox checkAdm;
    private javax.swing.JCheckBox checkAlterarCartucho;
    private javax.swing.JCheckBox checkAlterarImpr;
    private javax.swing.JCheckBox checkAtivo;
    private javax.swing.JCheckBox checkImpriRelCartuchos;
    private javax.swing.JCheckBox checkImprimirRelImpr;
    private javax.swing.JCheckBox checkInserirCartuchio;
    private javax.swing.JCheckBox checkInserirImpr;
    private javax.swing.JCheckBox checkRemoverCartucho;
    private javax.swing.JCheckBox checkRemoverImpr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
